version: '3.1'

services:
  mongo:
    image: mongo:latest
    container_name: models.docker
    ports:
      - '27017:27017'
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_storage:/data/db

volumes:
  mongo_storage:
